### PR TITLE
Select the longest matching key in matchMap

### LINKED ISSUE #136: valueMap does not backtrack correctly
If the map contains two strings where one is a prefix of the other and valueMap tries the shorter one first, it will never backtrack and try the longer one. Example:

``` scala
import org.parboiled2._
import scala.util._

class TestParser(val input: ParserInput) extends Parser {
  val values = Map("12" -> 12, "123" -> 123)

  def InputLine = rule {
    valueMap(values) ~ EOI
  }
}

object Hello extends App {
  val parser = new TestParser("123")
  parser.InputLine.run() match {
    case Success(x) => println(x)
    case Failure(e: ParseError) => sys.error(parser.formatError(e, new ErrorFormatter(showTraces = true)))
    case x => println(x)
  }
}
```

The expectation is to parse "123" successfully, but this example fails with:

```
java.lang.RuntimeException: Invalid input '3', expected 'EOI' (line 1, column 3):
123
  ^
```

As a side note, since the order we try the pairs in the map matters (even if backtracking worked), it would be nice to have a version that takes Seq[(String, T)]

### PR DESCRIPTION
**Pull request by barnardb**
Fixes #136

By checking keys from longest to shortest, we ensure that we always
select the longest matching key.

This fix requires sorting the keys each time the rule is invoked. If
#115 gets implemented, this could be improved to make use of it instead.

### CODE REVIEW

**Comment by barnardb** [comment]
Sorry, I wasn't thinking straight in writing that final comment. The map value isn't known until runtime, so of course the optimisation desired in #115 would be unhelpful.

File: parboiled-core/src/main/scala/org/parboiled2/Parser.scala [hunk 1]
```diff
@@ -449,7 +449,7 @@ abstract class Parser(initialValueStackSize: Int = 16,
    * THIS IS NOT PUBLIC API and might become hidden in future. Use only if you know what you are doing!
    */
   def __matchMap(m: Map[String, Any]): Boolean = {
-    val keys = m.keysIterator
+    val keys = m.keys.toSeq.sortBy(-_.length).iterator
```
Comment (sirthias) [inline parboiled-core/src/main/scala/org/parboiled2/Parser.scala]: I think we can actually make this more efficient.
We don't need to sort the whole map, only the prefix up until the match.
Check out [this SO answer](http://stackoverflow.com/questions/12639320/lazy-sorts-of-iterators-in-scala) for an idea of how this could be done.

**Comment by sirthias** [comment]
Thank you, Ben, and sorry for taking so long to get this merged!
